/*                                                                 */
/*        Version String                                           */
/*                                                                 */
/*        programed By Magic Book                                  */
/*                                                                 */

#ifndef __COLVERSION__

#define __COLVERSION__

#define ColVersion "SAN VGA/EGA DRIVER COLOR SETUP Version 1.2 (C) 1991-93 by Park,Kyu Hyun\n"
#define ColVersionNum "1.2"

#endif
