/*                                                                 */
/*        Version String                                           */
/*                                                                 */
/*        programed By Magic Book                                  */
/*                                                                 */

#ifndef __FONTVERSION__

#define __FONTVERSION__

#define FontVersion "HanGul Editor SAN Font Librarian Version 1.2 (C) 1991-93 by Park,Kyu Hyun\n"
#define FontVersionNum "1.2"

#endif
