/*                                                                 */
/*        Version String                                           */
/*                                                                 */
/*        programed By Magic Book                                  */
/*                                                                 */

#ifndef __SANVERSION__

#define __SANVERSION__

#define SanVersion "HanGul Editor SAN Version 1.2 (C) 1991,1992,1993 by Park,Kyu Hyun"
#define SanVersionNum "1.2"

#endif
