/*                                                                 */
/*        Version String                                           */
/*                                                                 */
/*        programed By Magic Book                                  */
/*                                                                 */

#ifndef __SETVERSION__

#define __SETVERSION__

#define SetVersion "HanGul Editor SAN SETUP Version 1.041 (C) 1991,1992 by Park,Kyu Hyun\n"
#define SetVersionNum "1.041"

#endif
